id: P002892
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18838
  title: བྲིས་སྐུ་མཐོང་བ་དོན་ལྡན།
  author: ''
  volumes:
    30504d9b35b8476c9540e03a5176728c:
      image_group_id: I1KG18855
      title: ''
      volume_number: 1
      total_pages: 628
      base_file: v001.txt
